apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: myapp-sa
  restartPolicy: Never
  containers:
    - name: debug
      image: amazon/aws-cli:2.11.17
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
      stdin: true
      tty: true
